project:
  type: website

website:
  title: "Optimising workflows in R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: 'Work Sans'
    monofont: 'Cutive Mono'

editor: visual

